{% set version = "0.36.0" %}
{% set sha256 = "9b6d04ad4dd34838c1b55a8ec4b69e8d7f3008a67d85ef1c35b49502c359b6d8" %}

package:
  name: rust-script
  version: {{ version }}

source:
  url: https://github.com/fornwall/rust-script/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --no-track --locked --verbose --root "${PREFIX}" --path .    # [not win]
    - cargo install --no-track --locked --verbose --root "%PREFIX%" --path .     # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
  run:
    - rust >=1.74

test:
  commands:
    - rust-script --version | grep -qF '{{ version }}'    # [not win]
    - rust-script --version | findstr "/C:{{ version }}"  # [win]
    - rust-script --expr 'println!("Hello, World!");' | grep -qF 'Hello, World!'         # [not win]
    - rust-script --expr "println!(\"Hello, World!\");" | findstr /B "/C:Hello, World!"  # [win]

about:
  home: https://rust-script.org
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Run Rust files and expressions without any setup or compilation necessary.
  description: |
    With rust-script Rust files and expressions can be executed just like a shell or Python script. Features include:
    - Caching compiled artifacts for speed.
    - Reading Cargo manifests embedded in Rust scripts.
    - Supporting executable Rust scripts via Unix shebangs and Windows file associations.
    - Using expressions as stream filters (i.e. for use in command pipelines).
    - Running unit tests and benchmarks from scripts.
    - Custom templates for command-line expressions and filters.
  doc_url: https://rust-script.org/
  dev_url: https://github.com/fornwall/rust-script

extra:
  recipe-maintainers:
    - tedil
    - dlaehnemann
    - mbhall88
